POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "SuperSponge123",
  "password": "gary"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "JohnDoe123",
  "password": "LMAO"
}

###
POST http://localhost:3001/api/login/sign-up
Content-Type: application/json

{
  "username": "T",
  "name": "S",
  "password": "Science"
}

###
POST http://localhost:3001/api/login/sign-up
Content-Type: application/json

{
  "username": "BuffLobster12",
  "name": "Larry Lobster",
  "password": "IlifetWeigHTs"
}