GET http://localhost:3001/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyU3BvbmdlMTIzIiwiaWQiOiI2MmEyNWFjZmMzYjgzYzNkMzA1ZmU3ZjEiLCJpYXQiOjE2NTcyMDI5MDgsImV4cCI6MTY1NzIzNTMwOH0.lXSLEjo8hH6ENK-KPCG_OSPOyv6G0bjt6PavgyFAygg

###

PUT http://localhost:3001/api/users/62cd8b9f25caf2d45d46edb1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyU3BvbmdlMTIzIiwiaWQiOiI2MmM3MTJjZDEzMGJhYzgxMjZmMDkzYmUiLCJpYXQiOjE2NTc2NDE0NjgsImV4cCI6MTY1NzY3Mzg2OH0.ghTJIcpidUvEZHC_bGaLNDgHgMVT3gIHHSCKc2WP3Xc

{
  "username": "BossMan101"
}

###
PUT http://localhost:3001/api/users/62cdac496a1c941e7ef24a75
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyU3BvbmdlMTIzIiwiaWQiOiI2MmM3MTJjZDEzMGJhYzgxMjZmMDkzYmUiLCJpYXQiOjE2NTc2NDM1MzYsImV4cCI6MTY1NzY3NTkzNn0.9VHs59iLPlh2M-7NH3-X8lyXSptiDc-HrWQBrQGSWzw

{
  "username": "BossMan101",
  "enabled": false
}

###
PUT http://localhost:3001/api/users/62cd8bae25caf2d45d46edb2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyU3BvbmdlMTIzIiwiaWQiOiI2MmM3MTJjZDEzMGJhYzgxMjZmMDkzYmUiLCJpYXQiOjE2NTc2NDE0NjgsImV4cCI6MTY1NzY3Mzg2OH0.ghTJIcpidUvEZHC_bGaLNDgHgMVT3gIHHSCKc2WP3Xc

{
  "enabled": true,
  "name": "Patrick Star"
}

###
PUT http://localhost:3001/api/users/62cd8bae25caf2d45d46edb2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN1cGVyU3BvbmdlMTIzIiwiaWQiOiI2MmM3MTJjZDEzMGJhYzgxMjZmMDkzYmUiLCJpYXQiOjE2NTc2NDE0NjgsImV4cCI6MTY1NzY3Mzg2OH0.ghTJIcpidUvEZHC_bGaLNDgHgMVT3gIHHSCKc2WP3Xc

{
  "enabled": false,
  "name": "Patrick Star"
}
